name: Gerar cobrinha

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite
  workflow_dispatch: # permite executar manualmente

jobs:
  gerar-cobrinha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar cobrinha SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Vitoria-Araujo
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit e push do SVG na branch output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

